# Generated by Django 4.2.4 on 2023-09-07 20:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Books",
            new_name="Book",
        ),
        migrations.RenameModel(
            old_name="Podcasts",
            new_name="Podcast",
        ),
    ]
